# refs: [Swift のビルドとテスト - GitHub ドキュメント](https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-swift)

name: CI

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:    # 手動実行を有効化

jobs:
  build:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      # refs: [swift-actions/setup-swift](https://github.com/swift-actions/setup-swift)
      - uses: swift-actions/setup-swift@v2

      - name: Get swift version
        run: swift --version
    
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Swift Build
        run: swift build

      - name: Run UnitTests
        run: swift test
        
  # SwiftLint

  # refs
  # [swift - How can I run swiftlint on GitHub Actions for linux? - Stack Overflow](https://stackoverflow.com/questions/72033107/how-can-i-run-swiftlint-on-github-actions-for-linux)
  # [realm/SwiftLint: A tool to enforce Swift style and conventions.](https://github.com/realm/SwiftLint)
        
  swiftlint:
    name: SwiftLint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:latest

    steps:
      - name: Checkout Branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
  
      - name: SwiftLint
        run: |
          swiftlint --reporter github-actions-logging --strict
